### ISSUE TITLE
Explanation to each question is not provided and one question is just lorem

### ISSUE THREAD

**Issue by piyushkdas0611** [wingkwong/react-quiz-component#109]
![Screenshot (5)](https://github.com/wingkwong/react-quiz-component/assets/96428820/5a513f3a-fc74-48a5-af9c-629070b05b3a)
![Screenshot (4)](https://github.com/wingkwong/react-quiz-component/assets/96428820/fa81e410-90e5-4d07-a73b-986522e3f622)

**Comment by piyushkdas0611** [comment]
Assign me this issue for improvement

**Comment by Shashankpantiitbhilai** [comment]
assign me this issue and please give it hacktober label

**Comment by wingkwong** [comment]
This is just for demonstration only ...
