### ISSUE TITLE
You cannot see the marks scored for each individual question at the end.

### ISSUE THREAD

**Issue by aabbi15** [wingkwong/react-quiz-component#112]
For example here is got 50 marks for 3 correct questions and it would be nice to see which questions gave me the 50 marks since it is not 20 marks per correct question (an evenly spread situation).

![image](https://github.com/wingkwong/react-quiz-component/assets/133003256/cb547dd3-e1ab-43b2-8112-bacd69448901)

**Comment by wingkwong** [comment]
So what is your proposal of the change? Appending the mark to the question?

**Comment by Aditya-Chaurasia11** [comment]
can you assign this to me?

**Comment by aabbi15** [comment]
> So what is your proposal of the change? Appending the mark to the question?

Yes. I will be able to do so but for it can you let me know what the scoring scheme is or where can I find it in the codebase? What questions hold what marks?

**Comment by wingkwong** [comment]
each question has `point`. The total point is simply the sum of the points of corrected questions.

ref:

```ts
{
  question: 'ReactJS is developed by _____?',
  questionType: 'text',
  answerSelectionType: 'single',
  answers: [
    'Google Engineers',
    'Facebook Engineers',
  ],
  correctAnswer: '2',
  messageForCorrectAnswer: 'Correct answer. Good job.',
  messageForIncorrectAnswer: 'Incorrect answer. Please try again.',
  explanation: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  point: '20',
  segment: segment.basic,
}
```

**Comment by aabbi15** [comment]
How does this look?
![image](https://github.com/wingkwong/react-quiz-component/assets/133003256/e618b23f-cd90-4c07-9206-696d09446a76)

![image](https://github.com/wingkwong/react-quiz-component/assets/133003256/31a83ef3-5771-4b5e-8240-89262f3386c3)


I added a new text span in **renderQuizResultQuestionsfunction** in  **Core.jsx** with the css "**answer-score**" added to styles.css

**Comment by wingkwong** [comment]
IMO it doesn't look good as it gives too much space there. What about making it as a tag or just append the wording to the question, e.g. `Q1: XXXXXX? (20 marks)`?

**Comment by aabbi15** [comment]
Does this look better?

![image](https://github.com/wingkwong/react-quiz-component/assets/133003256/63d46388-0c6e-455d-94dc-6d296c05ec9f)
![Uploading image.png…]()

**Comment by wingkwong** [comment]
I couldn't see the second photo. Based on the first one, I think it's fine.  I'd suggest to use `marks` instead of `Marks`. Also this text should be put in AppLocale as well so that people can configure it.

**Comment by aabbi15** [comment]
Cool I will do that.
Can you mark this issue as hacktoberfest and hacktoberfest-accepted as I want it to count as one of my contributions?

**Comment by wingkwong** [comment]
The repository has been labelled `hacktoberfest`, which means all PRs under this repository will be counted without adding the label one by one.

**Comment by aabbi15** [comment]
I changed to marks and now it is written using appLocale dynamically i will generate a pull request


![image](https://github.com/wingkwong/react-quiz-component/assets/133003256/0e5bdecf-a2b7-4899-8548-f08647750d40)
