### ISSUE TITLE
lint issues

### ISSUE THREAD

**Issue by wingkwong** [wingkwong/react-quiz-component#113]
- run `npm run lint` and fix all the issues

**Comment by vidhuUC** [comment]
Assign this issue to me. I can do it

**Comment by wingkwong** [comment]
@vidhuUC assigned.

**Comment by wingkwong** [comment]
@vidhuUC any updates?

**Comment by viditagrawal56** [comment]
Hey @wingkwong as the assignee has not responded can you assign me this issue I would love to work on it!

**Comment by viditagrawal56** [comment]
hey @wingkwong The link gives warning to remove the console.error lines. Should I just directly remove them or are they useful?

**Comment by wingkwong** [comment]
@viditagrawal56 Those are required to notify users for misconfigurations. You can set `no-console` to `off` in eslint config.

**Comment by viditagrawal56** [comment]
Hey @wingkwong the lint is giving an error that the line extends the length limit of 120. The line that exceeds this limit is an answer to a question so I cant remove anything from the line to make it fit the limit of 120. So should I just increase the limit?
If yes, then what should the new limit be?

**Comment by wingkwong** [comment]
you may disable this lint at this moment. I'll pick it up later on.

**Comment by viditagrawal56** [comment]
Hey @wingkwong the dangerouslySetInnerHTML property is setting off a warning, to fix it I think it will require DOMPurify to be imported to sanitizes the HTML before using the dangerouslySetInnerHTML.
This will require the dompurify to be installed.
So should I install dompurify or just disable the specific lint?

**Comment by wingkwong** [comment]
please disable it. We already have `dompurify.sanitize` in `rawMarkup` so it's fine.

```jsx
dangerouslySetInnerHTML={rawMarkup(...)}
```

**Comment by viditagrawal56** [comment]
@wingkwong the use of confirm in the code gives the no-restricted-globals lint error. Should I create a separate confirmation modal or just disable the lint?

**Comment by wingkwong** [comment]
@viditagrawal56 disable first. I'll take a look later. please note down all the errors / warnings for those you've disabled. Thanks.

**Comment by wingkwong** [comment]
@viditagrawal56 leave 5th one to me.

**Comment by viditagrawal56** [comment]
@wingkwong Sorry for not understanding, you mean disable the first lint error right?
Or do you mean I should just disable all the lint errors except the fifth one and make a note of all the disabled errors?

**Comment by wingkwong** [comment]
@viditagrawal56 yes disable only the fist one. for no-shadow and react/no-array-index-key, they can be fixed. If you have discord, free feel to ping me [here](https://discordapp.com/users/495466997304262658) for live discussion if necessary.

**Comment by viditagrawal56** [comment]
@wingkwong ok thanks!
