### ISSUE TITLE
Quiz can be center instead of top-right and not mobile responsive

### ISSUE THREAD

**Issue by Vijayabaskar56** [wingkwong/react-quiz-component#126]

**Comment by Vijayabaskar56** [comment]
I  can work on it , can you assign it to me

**Comment by wingkwong** [comment]
I believe you meant top-left (?). If one needs to center the component, they can add the style on the wrapper. The style shouldn't apply on the component itself. Also can you show some screenshots to show it is not mobile responsive?

**Comment by Vijayabaskar56** [comment]
yeah, my bad.

yeah, your right the style should be on the wrapper.

here is the screenshot.

![Screenshot from 2023-10-05 19-51-06](https://github.com/wingkwong/react-quiz-component/assets/84858449/e4b49cbb-e36c-4fab-a81e-978bc3f50df7)
see here the question and option is overflowing.

![Screenshot from 2023-10-05 19-57-50](https://github.com/wingkwong/react-quiz-component/assets/84858449/4c179fe5-4464-43b2-a2c2-893184dae728)
here is the demo of quiz component in center, which look good. please let me know

**Comment by wingkwong** [comment]
Ok. Please make it responsive to the outer wrapper.

**Comment by Vijayabaskar56** [comment]
got it. thanks
