### ISSUE TITLE
Localization and custom Header

### ISSUE THREAD

**Issue by aureliopetrone** [wingkwong/react-quiz-component#13]
Hi, I suggest you could add these features:

- Custom Header ( you can change the "X Questions" part)
- An option for change the text variables value (like the "default" header "Questions" text

I'm thankful for your component.

**Comment by aureliopetrone** [comment]
@wingkwong I've done this but I'm not so skilled in git. 

If you want I can share the code with you via Skype or mail.

**Comment by wingkwong** [comment]
@aureliopetrone Appreciate your help! I've sent your an email. Please check. Thanks.

**Comment by wingkwong** [comment]
@aureliopetrone are you still working on this issue?

**Comment by wingkwong** [comment]
Closing this issue as it has been done in v0.2.7.
