### ISSUE TITLE
Title: Enhancement Request: Show Quiz Progress During Quiz in React-Quiz Library

### ISSUE THREAD

**Issue by JayeshYadav99** [wingkwong/react-quiz-component#131]
Issue Description:

**Issue Summary:**
Currently, the React-Quiz library does not provide users with a visual indicator of their progress within a quiz. To improve the user experience and keep users informed about their progress, we propose adding a feature that shows users how many questions they've answered and how many questions remain in the quiz.

**Proposed Feature: Quiz Progress Indicator**

**Feature Details:**
- Display a progress bar or a simple text indicator (e.g., "Question X of Y") at the top or bottom of the quiz interface.
- The progress indicator should dynamically update as users answer questions, providing real-time feedback on their progress.
- The indicator should include the number of questions answered and the total number of questions in the quiz.
- The feature should be optional, allowing quiz creators to enable or disable it based on their preferences.

**Benefits:**
- Improved User Experience: Users will have a clear understanding of their progress within the quiz, making the experience more engaging and user-friendly.
- Reduced User Confusion: Users will know how many questions they need to complete, reducing uncertainty and improving engagement.
- Enhanced Engagement: A progress indicator encourages users to complete the quiz, as they can track their progress.

**Implementation Details:**
I will add a progress indicator feature to the React-Quiz library, ensuring that it is configurable and can be easily integrated into quiz interfaces.

**Acceptance Criteria:**
- The progress indicator is added to the library.
- The indicator updates dynamically as users answer questions.
- Quiz creators can enable or disable the feature through library configurations.
- The feature is thoroughly tested for functionality and compatibility.

**Additional Notes:**
This enhancement will enhance the usability of the React-Quiz library and make it more appealing to users who want to track their progress during quizzes.

**ScreenShots**
![image](https://github.com/wingkwong/react-quiz-component/assets/107855172/25f7c4f2-6348-4525-9efe-a3eb6dec216b)

**Priority:** Medium

**Labels:** enhancement, user experience, quiz, progress indicator

Please feel free to discuss and provide feedback on this proposed feature.****

**Comment by wingkwong** [comment]
progress bar would be nice.

**Comment by JayeshYadav99** [comment]
@wingkwong ,please assign me this issue i will make pr asap

**Comment by wingkwong** [comment]
Go ahead.

**Comment by JayeshYadav99** [comment]
@wingkwong ,please review my pull request

**Comment by JayeshYadav99** [comment]
@mrinmay7875 ,why you are making pr with assigning of issue

**Comment by wingkwong** [comment]
Oh I didn't aware that. However, Mrinmay's work is more closer to my expectation. 

@JayeshYadav99 can you just add `Question X of Y` only in your PR please? 
@mrinmay7875 next time please ask for assignment first to avoid duplicate work.

**Comment by JayeshYadav99** [comment]
@wingkwong ,I have made changes
