### ISSUE TITLE
Title: Enhancement Request: Add Multilingual Quiz Support using 'react-intl' in React-Quiz Library

### ISSUE THREAD

**Issue by JayeshYadav99** [wingkwong/react-quiz-component#132]
Issue Description:

**Issue Summary:**
The React-Quiz library currently lacks built-in multilingual support, making it challenging for users to create quizzes in multiple languages. To enhance the library's accessibility and usability for a global audience, we propose integrating the 'react-intl' library to enable effortless multilingual support.

**Proposed Feature: Multilingual Quiz Support using 'react-intl'**

**Feature Details:**
- Integrate the 'react-intl' library to facilitate localization and translation of quiz content.
- Allow quiz creators to define different sets of questions and answers for each supported language.
- Provide a language selection mechanism within the quiz interface, allowing users to switch between available languages.
- Implement language fallbacks to ensure a seamless user experience, even if a specific translation is missing.
- Enable quiz creators to manage translations through language-specific JSON files or a user-friendly interface.

**Benefits:**
- Enhanced Accessibility: Users can engage with quizzes in their preferred language, improving comprehension and user experience.
- Global Reach: The library becomes accessible to a wider audience, encouraging international users to create and participate in quizzes.
- Improved User Engagement: Multilingual support fosters inclusivity, encouraging diverse users to interact with the quiz content.

**Implementation Details:**
- Integrate the 'react-intl' library into the React-Quiz codebase.
- Design an intuitive interface for quiz creators to input questions and answers in multiple languages.
- Implement language selection components within the quiz interface.
- Provide clear documentation and guidelines on how to manage translations for quiz content.

**Acceptance Criteria:**
- The 'react-intl' library is successfully integrated into the React-Quiz codebase.
- Quiz creators can define and manage questions and answers in multiple languages.
- Users can switch between languages seamlessly during the quiz.
- Language fallbacks are implemented to handle missing translations gracefully.
- The feature is thoroughly tested for functionality and user experience.

**Additional Notes:**
Introducing multilingual support using the 'react-intl' library will make React-Quiz more accessible and user-friendly for a diverse range of users. It aligns with our goal of providing an inclusive and global quiz creation experience.

**Priority:** High

**Labels:** enhancement, multilingual-support, react-intl, user experience

Please feel free to discuss and provide feedback on this proposed feature.

**Comment by wingkwong** [comment]
I think it can be done simply feeding different languages to `quiz` and `appLocale`.
