### ISSUE TITLE
improve the filter design

### ISSUE THREAD

**Issue by VishakhaSainani** [wingkwong/react-quiz-component#141]
![React Quiz Component Demo - Google Chrome 21-10-2023 23_30_16](https://github.com/wingkwong/react-quiz-component/assets/113436770/158663b0-ec1d-4ba5-8fb6-5e35459e284d)
![React Quiz Component Demo - Google Chrome 21-10-2023 23_28_01](https://github.com/wingkwong/react-quiz-component/assets/113436770/027a5a1b-acd7-45c9-9bd6-93c3361968d8)
![React Quiz Component Demo - Google Chrome 21-10-2023 23_28_22](https://github.com/wingkwong/react-quiz-component/assets/113436770/ccd00822-7fc7-40b1-b35e-26928fb018bb)

**Comment by VishakhaSainani** [comment]
@wingkwong assign this issue to me.

**Comment by wingkwong** [comment]
For responsive, I think there is existing work already. You may focus on filter design.

**Comment by VishakhaSainani** [comment]
ok I am working on it, Thankyou.

**Comment by VishakhaSainani** [comment]
I have updates the design, check it out @wingkwong
