### ISSUE TITLE
Update lorem ipsum question

### ISSUE THREAD

**Issue by pranav514** [wingkwong/react-quiz-component#148]
New question regarding react needed to be added in the place of lorem ipsum question
![image](https://github.com/wingkwong/react-quiz-component/assets/76992202/a2b61736-6a35-4c42-979f-dd66aaebed9c)

**Comment by pranav514** [comment]
@wingkwong assign this issue me.....and what question you would like to add instead of this lorem ipsum question

**Comment by wingkwong** [comment]
Why we need to update this? It's for demo purpose only and not a real quiz for people.

**Comment by pranav514** [comment]
@wingkwong  instead of lorem ipsum question ,I think it will be better to add some real basic question, though it is not a real quiz but replacing  the lorem ipsum question will make it more better

**Comment by wingkwong** [comment]
then you may purpose a question and replace those 4 images.

**Comment by pranav514** [comment]
@wingkwong  following is the question proposed by me

![image](https://github.com/wingkwong/react-quiz-component/assets/76992202/2ab10b43-3f6c-4dd1-8620-269fc6b8fcd4)

pls review it

**Comment by wingkwong** [comment]
Well the purpose of this dummy question is to demonstrate the image feature. Please don't use text answers.
