### ISSUE TITLE
Support for ECMAScript Modules

### ISSUE THREAD

**Issue by matthewbcool** [wingkwong/react-quiz-component#150]
react-quiz-component library may not be fully compatible with [Astro](https://astro.build/) or Vite's module system out of the box. 

Astro uses Vite as its internal build engine, which supports ESM (ECMAScript Modules). However, not all npm packages support ESM. If the react-quiz-component library doesn't support ESM, you might need to adjust your vite config for it to work. Astro tries to convert the package to ESM so that import statements work (source (https://docs.astro.build/en/guides/imports/)).

**Comment by wingkwong** [comment]
@matthewbcool can you ping me at [Discord](https://discordapp.com/users/495466997304262658) for the discussion?

**Comment by matthewbcool** [comment]
> @matthewbcool can you ping me at [Discord](https://discordapp.com/users/495466997304262658) for the discussion?

Thank you kindly for taking a look, unfortunately, I'm not able to connect with you using that discord link.

Apologies if this issue lacks context, I don't deeply understand the root issue. 

I tried troubleshooting the issue in [Astro's server](https://discord.gg/astro-lounge-830184174198718474) with more details [in a thread here](https://discord.com/channels/830184174198718474/1168211097015292025/1168211097015292025).

Happy to discuss the issue more to see where I can help and appreciate any suggestions you can give.

**Comment by wingkwong** [comment]
Just ping you at Discord.

**Comment by matthewbcool** [comment]
Resolved. Thanks @wingkwong.  

For folks using Astro with mdx, use an astro file to import the component and don't forget to use the custom attribute `client:only="react"` when you import into the  `.astro` file.  e.g: `<YourQuiz client:only="react"/>`
