### ISSUE TITLE
Consider passing props for styling. 

### ISSUE THREAD

**Issue by sureshHARDIYA** [wingkwong/react-quiz-component#16]
Would be nice to have props for styling `main container`, `individual questions` and `even options`

Regards,

**Comment by wingkwong** [comment]
@sureshHARDIYA I've seen you made some changes. Please make a PR to v0.2.6 when it is ready. Thanks.

**Comment by sureshHARDIYA** [comment]
# Features Implemented is:

- Show total question when showing individual question like Question (1/15) which indicates there are total `15` questions and this is first one.
- Show total correct and total incorrect answer on the header. 
- Made a few Design changes. I don't feel, we should enforce a lot of design on the container. If we do so, someone who is using this component will not have design flexibility. 
- I am planning on passing `props` for `outerContainer` class, `question` container class and `option` container class. This will allow users to change design for `questions`, `options` and outer `div`. 
- Allow markdown features when writing the question. I wanted to format some text using markdown. So, if you use my version, it supports markdown. It supports headers, text formatting, and links without any problems. 

You can see all these changes https://skmukhiya.netlify.com/mentalHealthQuiz

Thanks for creating this library. It allowed me to include simple quiz like these without much effort.

**Comment by wingkwong** [comment]
@sureshHARDIYA That's excellent. Please make a PR to branch v0.2.6.

**Comment by wingkwong** [comment]
Closed this issue due to inactivity.
