### ISSUE TITLE
Prop to disable "Continue till answered correctly"

### ISSUE THREAD

**Issue by a-ssassi-n** [wingkwong/react-quiz-component#17]
Is there any way to take the input from the user only once? So when the user clicks on an answer (Maybe correct or incorrect), they should not be able to change the answer when this prop is set to false. (`continueTillCorrect={false}`)

Also when this prop is set to `false`, we could auto click on Next button after 1-2 seconds timeout (Just additional suggestion)

**Comment by wingkwong** [comment]
@a-ssassi-n this feature has been introduced in version 0.2.6
