### ISSUE TITLE
Timer feature is not working properly

### ISSUE THREAD

**Issue by trash369** [wingkwong/react-quiz-component#203]
**Version:**
"react-quiz-component": "^0.7.1",

As per the doc, we can add timer to our quiz. but there is no any timer displaying after starting the quiz. 

`<Quiz className={styles.quizContainer} quiz={data?.quiz} timer={10} shuffle={true} shuffleAnswer={true} />} `

**Comment by wingkwong** [comment]
It's in develop branch. Will be released in 0.8.0 in the coming days.

**Comment by trash369** [comment]
ah ok @wingkwong thank you so much
