### ISSUE TITLE
how to change startQuizBtn's content？how to set checkbox?

### ISSUE THREAD

**Issue by harry0071** [wingkwong/react-quiz-component#21]
1️⃣如何改变开始测验按钮的文本，现在默认是英文的Start Quiz，用户能否手动修改成“开始测验”？
2️⃣目前只支持单选，能否支持checkbox多选框？

**Comment by wingkwong** [comment]
1. We'll have more customisations in the further release. 
2. Checkbox will be supported in the further release.

**Comment by wingkwong** [comment]
[1] has been addressed in v0.2.7

**Comment by PTBKoo** [comment]
Love this quiz component, just started implementing this for my students. Was wondering if you had an ETA for selecting multiple answers as checkboxes? and any possibility to add a points/score system?

**Comment by wingkwong** [comment]
@PTBKoo Thanks for the support! I think I'll implement the point/score system in this week first. For selecting multiple answers, I'll do it after that. I'll create a new issue for these two requests.

**Comment by wingkwong** [comment]
Closed this issue. See #25 & #26.
