### ISSUE TITLE
Show an image and text as a question

### ISSUE THREAD

**Issue by EinarHm** [wingkwong/react-quiz-component#24]
Hello i want to know if its posible to show an image and a text in a question

**Comment by wingkwong** [comment]
@EinarHm It is not available in the current version. Will be introduced in the next release.

**Comment by EinarHm** [comment]
@wingkwong cool ! is there a release date for your next version ?

**Comment by wingkwong** [comment]
@EinarHm within this week

**Comment by wingkwong** [comment]
@EinarHm You can use markdown to show the image and the text in v0.2.8.
