### ISSUE TITLE
In version 0.8.2 it throw error Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by IamAhsanMani** [wingkwong/react-quiz-component#309]
I want to use this package in my project but don't know why it throw error `Cannot read properties of null (reading 'useState')`.

I even try it on codesandbox.
here is codsandbox link https://codesandbox.io/p/sandbox/beautiful-austin-vdk8cp?workspaceId=7fe15d62-b82e-4f84-82f1-c0f57b4367e3

In version ^0.2.6 it work like here https://codesandbox.io/p/sandbox/magical-quiz-xt2l1

**Comment by wingkwong** [comment]
couldn't access the first sandbox

![image](https://github.com/user-attachments/assets/697ddf80-8c83-4a7a-9212-2c518b30fbaf)

**Comment by IamAhsanMani** [comment]
@wingkwong try now link updated.

https://codesandbox.io/p/sandbox/beautiful-austin-vdk8cp?workspaceId=7fe15d62-b82e-4f84-82f1-c0f57b4367e3

**Comment by wingkwong** [comment]
I haven't checked in depth. Just skimmed through once, have you tried bumping your react version? Currently 0.8.2 is using react `^18.2.0` while your sandbox is still using 16. Also same for `react-dom`.

**Comment by IamAhsanMani** [comment]
Hello @wingkwong as you said i upgraded by project packages to latest versions.

Here is my package.json
<img width="329" alt="package" src="https://github.com/user-attachments/assets/8978ab23-a012-4148-8d70-0615d3c56ff1">

But there is still same useState error
<img width="1440" alt="Screenshot 2024-09-21 at 2 54 58 PM" src="https://github.com/user-attachments/assets/d7f35ac1-a888-49fe-8414-0a4f022e7a5f">


Below is how my QuizPage.js look like
https://gist.github.com/IamAhsanMani/ea3c8da7de1e21278185b6a7b7320f6d

and this is how my App.js look like,
https://gist.github.com/IamAhsanMani/94f8e4814c485bf0234fa5fbbabb9d2b

and index.js
https://gist.github.com/IamAhsanMani/f52f75bd2f3f826665eb316cb28d1d21

Don't know what is the issue if you please help me out it would be great

**Comment by wingkwong** [comment]
I didn't see the error in your updated sandbox.

**Comment by IamAhsanMani** [comment]
@wingkwong No the error is generating in my local project.

**Comment by wingkwong** [comment]
The reported issue was due to the outdated react version, which was proven after you upgraded the version in the sandbox. I can't really help if this happens in your local project. Probably you may cross check with the sandbox one to see the difference or try remove node_modules and reinstall again.

**Comment by IamAhsanMani** [comment]
Issue resolved by upgrading to react and react-dom latest version and plus make sure to clear cache and node_module and reinstall.
