### ISSUE TITLE
On selecting multiple select correct anwser it add undefined class to the button instead of correct

### ISSUE THREAD

**Issue by IamAhsanMani** [wingkwong/react-quiz-component#317]
https://github.com/user-attachments/assets/13a89e4e-2c19-42f5-8637-d3f826cc2a21

Check this video

**Comment by IamAhsanMani** [comment]
@wingkwong if i pass the showInstantFeedback to quiz it then work fine there bug in className assigning could you please fix it need urgent these changes

**Comment by wingkwong** [comment]
please upgrade to 0.9.0

**Comment by IamAhsanMani** [comment]
Hi, @wingkwong 

Check it out issue is still at here on select 1 and 2nd option it work fine when select 3rd option it remove correct or incorrrect class instead of adding it to all 3 options.


https://github.com/user-attachments/assets/05ef44a9-dd73-4308-ae2c-3d354b033f91

**Comment by wingkwong** [comment]
please create a new issue with sandbox
