### ISSUE TITLE
Getting error during the middle of quiz while clicking an answer

### ISSUE THREAD

**Issue by PTBKoo** [wingkwong/react-quiz-component#32]
Doesnt happen all the time but happens while clicking an answer.

TypeError: correct.includes is not a function

![image](https://user-images.githubusercontent.com/29348754/62749933-2fc38b00-ba13-11e9-9ffe-230303442e8b.png)

**Comment by wingkwong** [comment]
@PTBKoo 
could you provide the following info please? 
- What props you pass to <Quiz/>?
- What is the question type of the question you are answering when you encounter this error?

**Comment by PTBKoo** [comment]
The question was a multiple answer type when I got the error.

As for props Im just passing in quiz data and shuffle props.

**Comment by PTBKoo** [comment]
Removed all props except data props and still get the error
