### ISSUE TITLE
Make disable attribute on anwser button as optional

### ISSUE THREAD

**Issue by IamAhsanMani** [wingkwong/react-quiz-component#332]
Hello @wingkwong, i am thinking to make disable attribute as an optional for answers buttons. The idea is to allow user to select change anwsers until he/she click next button. Because may be they mistakely select an answers and want to change it.

this disable optional method will not apply if showInstantFeedback is true.

<img width="1123" alt="Screenshot 2024-09-28 at 9 43 39 AM" src="https://github.com/user-attachments/assets/ebd75d53-efe4-4090-b095-14e3885c3115">

**Comment by wingkwong** [comment]
your screenshot is not visible

**Comment by IamAhsanMani** [comment]
@wingkwong check now please

**Comment by Dhruv6397** [comment]
```

<button
            type="button"
            disabled={!showInstantFeedback && answerButtons[index].disabled}
            className={`${answerButtons[index].className || ''} answerBtn btn`}
            onClick={() => (revealAnswerOnSubmit ? onSelectAnswer(index) : onClickAnswer(index))}
          >
          
 ```
