### ISSUE TITLE
Display correct aswer AFTER you click Next

### ISSUE THREAD

**Issue by marcopolox** [wingkwong/react-quiz-component#52]
Instead of giving instant answer upon making a choice, it would make more sense to display the correct answer AFTER you click the Next button. That way you can a) change your mind as many times you want before "submitting" a choice/answer and b) invoke an API to check the answer if your questions are served via remote services for example.

**Comment by wingkwong** [comment]
Handled in 0.4.0. See `revealAnswerOnSubmit` and `allowNavigation`.
