### ISSUE TITLE
Custom result page is not displayed

### ISSUE THREAD

**Issue by beliayeu** [wingkwong/react-quiz-component#54]
### Steps to reproduce
* configure quiz per [Enabling Custom Result Page](https://github.com/wingkwong/react-quiz-component#enabling-custom-result-page)
* complete the quiz

**Actual result:** custom result page is not rendered
**Expected result:** custom result page is rendered

### Notes
* works fine in 0.3.4
* seems regression after https://github.com/wingkwong/react-quiz-component/commit/933e506c948a5bf26a6e3abfc0643b99e0934dc0

**Comment by wingkwong** [comment]
@akmil  pls take a look
