### ISSUE TITLE
Not showing explanation when answer is incorrect.

### ISSUE THREAD

**Issue by 007AMAN007** [wingkwong/react-quiz-component#69]
Hi, I am using this package past 1 month. I have enabled the ```showInstantFeedback``` but it's only showing the explanation on correct answer not on incorrect answer. Why ? How we can enable that ?

**Comment by wingkwong** [comment]
Explanation (i.e. `explanation`) is shown in the result page. Instant feedbacks (`messageForCorrectAnswer` or `messageForIncorrectAnswer`) are shown after answering the question.
