### ISSUE TITLE
_marked.default

### ISSUE THREAD

**Issue by hypo-thesis** [wingkwong/react-quiz-component#79]
There is a huge type error here upon installing and using a simple  `<Quiz quiz={quiz} />`

What to do? How to get it working?

**Comment by wingkwong** [comment]
I don't see that error. Mind to share more how you install or the version?

**Comment by hypo-thesis** [comment]
> I don't see that error. Mind to share more how you install or the version?

https://codesandbox.io/s/green-dawn-tjgc09?file=/src/App.js:5290-5311 

Version 0.4.0

**Comment by realisticattorney** [comment]
did you fix it?

**Comment by wingkwong** [comment]
@realisticattorney Not yet. Haven't got time to look into this issue yet.

**Comment by justoverclockl** [comment]
same error

**Comment by mrruby** [comment]
Any update about this, same issue with gatsby and yarn

**Comment by Gr33nLight** [comment]
I can check on this

**Comment by Gr33nLight** [comment]
Apparently it has to do with a compatibility issue with the version of the marked module, that doesn't seem to support cjs anymore, especially if used with webpack. Here they talk about version 4.0.0 onwards:
https://github.com/markedjs/marked/issues/2265

Some ugly fixes are available but a clean solution is not available yet it seems..

**Comment by wingkwong** [comment]
Please try on 0.5.0

**Comment by SaadBazaz** [comment]
> Same here.
> 
> Works fine if pulling code from https://github.com/wingkwong/react-quiz-component/tree/develop/src/lib
> 
> Error happens once installing module via yarn.

Still facing this issue. However, I did the above (Downloaded the code as zip, extracted it to my project's `components` folder, and imported directly)... and voila. It works. Good temporary solution.

**Comment by wingkwong** [comment]
fixed in 0.5.1
