### ISSUE TITLE
Shuffle variants

### ISSUE THREAD

**Issue by asqararslonov** [wingkwong/react-quiz-component#88]
Hi there,
I want to shuffle variants of questions. It will be like shuffle questions but for variants

**Comment by wingkwong** [comment]
I'm not sure what you mean. Could you elaborate more or provide some examples?

**Comment by asqararslonov** [comment]
> I'm not sure what you mean. Could you elaborate more or provide some examples?

So I made answers and all of them correctAnswer is equal to 1. So I want to make random options and that time correctAnswer must change to random correct answer too. That's what I want

**Comment by asqararslonov** [comment]
I tried with ChatGPT. I only made shuffle options of questions. Btw correctAnswer didn't changed to correct random one

**Comment by wingkwong** [comment]
Ok. `shuffleAnswer` hasn't implemented yet.

**Comment by Shariar-Hasan** [comment]
hey dear @wingkwong ,
may i first clear out the issue?
is it like this ,
you want to shuffle the answers too.
for example:
"answers": [
      "this.getState()",
      "this.prototype.stateValue",
      "this.state",
      "this.values"
],
"correctAnswer": "3",

after a shuffle, it will look like:
"answers": [
        "this.prototype.stateValue",
        "this.getState()",
        "this.values"
        "this.state",
  ],
  "correctAnswer": "4",
      
   if this is what you want, then can you assign the work to me, i feel like i can do it.

**Comment by wingkwong** [comment]
Yes. Go ahead.
