### ISSUE TITLE
Next button navigates to top of page when clicked

### ISSUE THREAD

**Issue by asqararslonov** [wingkwong/react-quiz-component#90]
Hi there
I have a large page and at the bottom, I have a quiz. when I click the next button to get the next question, it scrolls up(navigates to the top) and it's uncomfortable to scroll down every question. is there any way to fix it?

**Comment by vidhuUC** [comment]
Is this issue same as [Issue 91](https://github.com/wingkwong/react-quiz-component/issues/91) ?

**Comment by wingkwong** [comment]
True. Closing this one as it is duplicate.
