### ISSUE TITLE
When I click next button It scrolls to top

### ISSUE THREAD

**Issue by asqararslonov** [wingkwong/react-quiz-component#91]
Hello there
So I have large content and when users click the following button it scrolls to the top and users need to scroll down for selecting an answer and finish the quiz. But it's uncomfortable to scroll down every time for every question. Please fix it

**Comment by Ashik763** [comment]
Hey @asqararslonov, I want to contribute to this issue.

**Comment by wingkwong** [comment]
@Ashik763 assigned. suggest to have a new prop to control disable the scrolling.

**Comment by asqararslonov** [comment]
@wingkwong just remove that line with windows.scroll

**Comment by wingkwong** [comment]
@asqararslonov Simply removing is not a good solution. In fact can you elaborate more your case? A video to demonstrate would be better. If I have a long content, then I click next button, it should scroll back to the question in general.

**Comment by wingkwong** [comment]
Ok I just tested your site. I got what you mean. It should scroll to the top of the wrapper instead of the whole window.

**Comment by wingkwong** [comment]
@Ashik763 are you still working on it?

**Comment by Ashik763** [comment]
Yes,I am on it.

**Comment by wingkwong** [comment]
@Ashik763 you may try [this](http://leksika.uz/grammar/2) to understand the above case. 

What you need to do is 
- fix the scrolling behaviour - scroll to the top of the quiz wrapper instead of the window.
- add a flag to disable scrolling

**Comment by wingkwong** [comment]
@Ashik763 any ETA? I'm planning to have a release soon.
