### ISSUE TITLE
No presence of start page

### ISSUE THREAD

**Issue by devendra66** [wingkwong/react-quiz-component#94]
can I add front page as it is not showing

**Comment by wingkwong** [comment]
I don't quite understand what you mean. You mean the quiz synopsis in the demo site?

**Comment by devendra66** [comment]
Your first page starts from question not the intro page so can I fix that bug

**Comment by wingkwong** [comment]
This can be configurable. You can simply bring the intro page back by not setting `disableSynopsis`. Why would this be a bug?
